import { getLocalizedHref } from '../i18n';
import type { LotusThemeConfig } from '../theme';
import type {
  DocsNavItem,
  DocsSidebarItem,
  SidebarContentEntry,
} from './types';

export function normalizeAutogenerateDirectory(directory: string): string {
  return directory.trim().replace(/^\/+|\/+$/g, '');
}

function sortNavItems(items: DocsNavItem[]): DocsNavItem[] {
  return [...items].sort((left, right) => {
    if (left.order !== right.order) {
      return left.order - right.order;
    }

    return left.title.localeCompare(right.title);
  });
}

function entryToNavItem(
  config: LotusThemeConfig,
  entry: SidebarContentEntry,
  section: string | undefined,
  localeKey: string,
): DocsNavItem {
  return {
    title: entry.title,
    href: getLocalizedHref(config, entry.slug, localeKey),
    slug: entry.slug,
    section,
    order: entry.order,
  };
}

function navItemToSidebarItem(item: DocsNavItem): DocsSidebarItem {
  return {
    label: item.title,
    href: item.href,
    slug: item.slug,
  };
}

export function getAutogeneratedEntries(
  entries: SidebarContentEntry[],
  directory: string,
): SidebarContentEntry[] {
  const normalizedDirectory = normalizeAutogenerateDirectory(directory);

  return entries.filter((entry) => {
    if (entry.hidden || entry.slug === 'index') {
      return false;
    }

    if (!normalizedDirectory) {
      return !entry.slug.includes('/');
    }

    return entry.slug.startsWith(`${normalizedDirectory}/`);
  });
}

export function generateSidebarItems(
  config: LotusThemeConfig,
  entries: SidebarContentEntry[],
  directory: string,
  localeKey: string,
): DocsSidebarItem[] {
  return sortNavItems(
    getAutogeneratedEntries(entries, directory).map((entry) =>
      entryToNavItem(config, entry, undefined, localeKey),
    ),
  ).map(navItemToSidebarItem);
}
