import { describe, expect, it } from 'vitest';
import { resolveLotusConfig } from '../src/lib/config';
import {
  getDefaultLocale,
  getLanguageDirection,
  getLocalizedHref,
  getLocalizedMarkdownHref,
  getLocalizedSlugFromEntryId,
  getLocales,
  localizeDocsHref,
} from '../src/lib/i18n';
import {
  generateSidebarItems,
  getAutogeneratedEntries,
} from '../src/lib/sidebar/autogenerate';
import { resolveSidebars } from '../src/lib/sidebar/resolve';
import type { SidebarContentEntry } from '../src/lib/sidebar/types';

const localizedConfig = resolveLotusConfig({
  docsBase: '/docs',
  locales: {
    root: {
      label: 'English',
      lang: 'en',
      directory: 'en',
    },
    'zh-cn': {
      label: '简体中文',
      lang: 'zh-CN',
      directory: 'zh-cn',
    },
  },
});

const sidebarEntries: SidebarContentEntry[] = [
  { slug: 'index', title: 'Home', order: 0, hidden: false },
  { slug: 'overview', title: 'Overview', order: 1, hidden: false },
  { slug: 'installation', title: 'Installation', order: 2, hidden: false },
  { slug: 'configuration/appearance', title: 'Appearance', order: 20, hidden: false },
  { slug: 'configuration/navigation', title: 'Navigation', order: 10, hidden: false },
  { slug: 'configuration/advanced/cache', title: 'Cache', order: 30, hidden: false },
  { slug: 'configuration/secret', title: 'Secret', order: 40, hidden: true },
  { slug: 'components/card', title: 'Card', order: 1, hidden: false },
];

describe('localized navigation', () => {
  it('normalizes root and prefixed locales', () => {
    expect(getDefaultLocale(localizedConfig)).toMatchObject({
      key: 'root',
      directory: 'en',
      pathPrefix: '',
    });
    expect(getLocales(localizedConfig).map((locale) => locale.pathPrefix)).toEqual(['', 'zh-cn']);
  });

  it('detects rtl language direction from language code', () => {
    expect(getLanguageDirection('ar')).toBe('rtl');
    expect(getLanguageDirection('ar-EG')).toBe('rtl');
    expect(getLanguageDirection('zh-CN')).toBe('ltr');
  });

  it('maps localized entry ids and slug overrides to public slugs', () => {
    expect(getLocalizedSlugFromEntryId(localizedConfig, 'en/overview')).toMatchObject({
      locale: { key: 'root' },
      slug: 'overview',
    });
    expect(getLocalizedSlugFromEntryId(localizedConfig, 'zh-cn/configuration/search')).toMatchObject({
      locale: { key: 'zh-cn' },
      slug: 'configuration/search',
    });
    expect(getLocalizedSlugFromEntryId(localizedConfig, 'zh-cn/reference/cli', 'api/cli')).toMatchObject({
      locale: { key: 'zh-cn' },
      slug: 'api/cli',
    });
  });

  it('builds localized html and markdown hrefs under docsBase', () => {
    expect(getLocalizedHref(localizedConfig, 'index', 'root')).toBe('/docs');
    expect(getLocalizedHref(localizedConfig, 'installation', 'zh-cn')).toBe(
      '/docs/zh-cn/installation/',
    );
    expect(getLocalizedMarkdownHref(localizedConfig, 'index', 'root')).toBe('/docs/index.md');
    expect(getLocalizedMarkdownHref(localizedConfig, 'installation', 'zh-cn')).toBe(
      '/docs/zh-cn/installation.md',
    );
  });

  it('localizes docs links while preserving external and non-docs links', () => {
    expect(localizeDocsHref(localizedConfig, 'https://example.com', 'zh-cn')).toBe(
      'https://example.com',
    );
    expect(localizeDocsHref(localizedConfig, '/pricing/', 'zh-cn')).toBe('/pricing/');
    expect(localizeDocsHref(localizedConfig, '/docs/configuration/search/', 'zh-cn')).toBe(
      '/docs/zh-cn/configuration/search/',
    );
  });
});

describe('sidebar navigation', () => {
  it('filters autogenerated entries by directory, depth, exclude, and hidden state', () => {
    const generated = getAutogeneratedEntries(sidebarEntries, {
      directory: 'configuration',
      depth: 1,
      exclude: 'navigation',
    });

    expect(generated.map((entry) => entry.slug)).toEqual(['configuration/appearance']);
  });

  it('generates flat and tree sidebar items from content entries', () => {
    const config = resolveLotusConfig({ docsBase: '/docs' });
    const flatItems = generateSidebarItems(config, sidebarEntries, {
      directory: 'configuration',
    }, 'root');
    const treeItems = generateSidebarItems(config, sidebarEntries, {
      directory: 'configuration',
      structure: 'tree',
    }, 'root');

    expect(flatItems.map((item) => [item.label, item.href])).toEqual([
      ['Navigation', '/docs/configuration/navigation/'],
      ['Appearance', '/docs/configuration/appearance/'],
      ['Cache', '/docs/configuration/advanced/cache/'],
    ]);
    expect(treeItems).toMatchObject([
      { label: 'Navigation' },
      { label: 'Appearance' },
      {
        label: 'Advanced',
        items: [{ label: 'Cache', href: '/docs/configuration/advanced/cache/' }],
      },
    ]);
  });

  it('resolves strings, links, groups, autogenerate items, badges, and translated labels', async () => {
    const config = resolveLotusConfig({
      ...localizedConfig,
      sidebars: [
        {
          slug: 'guide',
          label: 'Guides',
          items: [
            {
              label: 'GitHub',
              translations: { 'zh-cn': '代码仓库' },
              link: 'https://github.com/prosefly/astro-theme-lotus',
              icon: 'simple-icons:github',
              badge: { label: 'New', position: 'trailing', color: 'success' },
            },
            {
              label: 'Getting Started',
              translations: { 'zh-cn': '入门' },
              items: [
                'overview',
                'installation',
                {
                  label: 'Configuration',
                  translations: { 'zh-cn': '配置' },
                  items: [{ autogenerate: { directory: 'configuration', depth: 1 } }],
                },
              ],
            },
          ],
        },
        {
          label: 'Components',
          items: [{ autogenerate: { directory: 'components' } }],
        },
      ],
    });

    const resolved = await resolveSidebars(config, sidebarEntries, 'zh-cn');

    expect(resolved.issues).toEqual([]);
    expect(resolved.sidebars.guide.links[0]).toMatchObject({
      label: '代码仓库',
      href: 'https://github.com/prosefly/astro-theme-lotus',
      external: true,
      icon: 'simple-icons:github',
      badge: { label: 'New', position: 'trailing', color: 'success' },
    });
    expect(resolved.sidebars.guide.groups[0]).toMatchObject({
      title: '入门',
      items: [
        { label: 'Overview', href: '/docs/zh-cn/overview/' },
        { label: 'Installation', href: '/docs/zh-cn/installation/' },
        {
          label: '配置',
          items: [
            { label: 'Navigation', href: '/docs/zh-cn/configuration/navigation/' },
            { label: 'Appearance', href: '/docs/zh-cn/configuration/appearance/' },
          ],
        },
      ],
    });
    expect(resolved.sidebars.components.links).toEqual([
      {
        label: 'Card',
        href: '/docs/zh-cn/components/card/',
        order: 1,
        slug: 'components/card',
      },
    ]);
  });

  it('supports promise sidebar items', async () => {
    const config = resolveLotusConfig({
      sidebars: [
        {
          label: 'API',
          items: Promise.resolve([
            { label: 'List pets', link: '/api/endpoints/pets/listpets/' },
          ]),
        },
      ],
    });

    const resolved = await resolveSidebars(config, sidebarEntries, 'root');

    expect(resolved.issues).toEqual([]);
    expect(resolved.sidebars.api.links).toEqual([
      {
        label: 'List pets',
        href: '/api/endpoints/pets/listpets/',
        external: false,
        icon: undefined,
        badge: undefined,
        slug: undefined,
      },
    ]);
  });

  it('reports duplicate sections, missing entries, and empty autogenerate groups', async () => {
    const config = resolveLotusConfig({
      sidebars: [
        { label: 'Guides', items: ['missing'] },
        { label: 'Guides', items: [{ autogenerate: { directory: 'empty' } }] },
      ],
    });

    const resolved = await resolveSidebars(config, sidebarEntries, 'root');

    expect(resolved.issues).toEqual([
      { type: 'duplicate-section', sectionSlug: 'guides', labels: ['Guides', 'Guides'] },
      { type: 'missing-entry', sectionSlug: 'guides', slug: 'missing' },
      { type: 'empty-autogenerate', sectionSlug: 'guides', directory: 'empty' },
    ]);
  });
});
