import { getCollection, type CollectionEntry } from 'astro:content';
import rawThemeConfig from 'virtual:prosefly/lotus/config';
import {
  normalizeDocsBasePath,
  type LotusThemeConfig,
  type SidebarAutogenerateItem,
  type SidebarConfig,
  type SidebarGroupItem,
  type SidebarItemConfig,
  type SidebarLinkItem,
} from './theme';

type DocsEntry = CollectionEntry<'docs'>;
const themeConfig = rawThemeConfig as LotusThemeConfig;

export interface DocsNavItem {
  title: string;
  href: string;
  slug: string;
  section?: string;
  order: number;
}

export interface DocsSidebarItem {
  label: string;
  href?: string;
  external?: boolean;
  icon?: string;
  slug?: string;
  items?: DocsSidebarItem[];
}

export interface DocsSidebarGroupNav {
  title: string;
  items: DocsSidebarItem[];
}

export interface DocsSidebarNav {
  links: DocsSidebarItem[];
  groups: DocsSidebarGroupNav[];
}

export interface DocsSectionNav {
  slug: string;
  label: string;
  icon?: string;
  href: string;
  active: boolean;
  items: DocsNavItem[];
}

function getEntryOrder(entry: DocsEntry): number {
  return entry.data.order ?? Number.MAX_SAFE_INTEGER;
}

export function getEntrySection(entry: DocsEntry): string | undefined {
  if (entry.id === 'index') {
    return entry.data.section;
  }

  return entry.data.section ?? entry.id.split('/')[0];
}

function toNavItem(entry: DocsEntry): DocsNavItem {
  return {
    title: entry.data.title,
    href: entryToHref(entry),
    slug: entry.id,
    section: getEntrySection(entry),
    order: getEntryOrder(entry),
  };
}

function navItemToSidebarItem(item: DocsNavItem): DocsSidebarItem {
  return {
    label: item.title,
    href: item.href,
    slug: item.slug,
  };
}

function slugToTitle(slug: string): string {
  const segment = slug.split('/').filter(Boolean).at(-1) ?? slug;

  return segment
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function slugifyLabel(label: string): string {
  return label
    .trim()
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function getSidebarSectionSlug(sidebar: SidebarConfig): string {
  return sidebar.slug ?? slugifyLabel(sidebar.label);
}

function slugToHref(slug: string): string {
  const basePath = normalizeDocsBasePath(themeConfig.docsBase);
  const normalizedSlug = slug.replace(/^\/+|\/+$/g, '');

  if (!normalizedSlug || normalizedSlug === 'index') {
    return basePath === '/' ? '/' : `${basePath}/`;
  }

  return basePath === '/' ? `/${normalizedSlug}/` : `${basePath}/${normalizedSlug}/`;
}

function isExternalLink(link: string): boolean {
  return /^[a-z][a-z\d+.-]*:/i.test(link) || link.startsWith('//');
}

function normalizeDirectory(directory: string): string {
  return directory.trim().replace(/^\/+|\/+$/g, '');
}

function isLinkItem(item: SidebarItemConfig): item is SidebarLinkItem {
  return typeof item === 'object' && item !== null && 'link' in item;
}

function isGroupItem(item: SidebarItemConfig): item is SidebarGroupItem {
  return typeof item === 'object' && item !== null && 'items' in item;
}

function isAutogenerateItem(item: SidebarItemConfig): item is SidebarAutogenerateItem {
  return typeof item === 'object' && item !== null && 'autogenerate' in item;
}

function getEntryMap(entries: DocsEntry[]): Map<string, DocsEntry> {
  return new Map(entries.map((entry) => [entry.id, entry]));
}

function getEntryForSlug(entriesById: Map<string, DocsEntry>, slug: string): DocsEntry | undefined {
  const normalizedSlug = slug.replace(/^\/+|\/+$/g, '');

  return entriesById.get(normalizedSlug || 'index');
}

function getAutogeneratedEntries(entries: DocsEntry[], directory: string): DocsEntry[] {
  const normalizedDirectory = normalizeDirectory(directory);

  return entries.filter((entry) => {
    if (entry.id === 'index') {
      return false;
    }

    if (!normalizedDirectory) {
      return !entry.id.includes('/');
    }

    return entry.id.startsWith(`${normalizedDirectory}/`);
  });
}

function entryToSidebarItem(entry: DocsEntry): DocsSidebarItem {
  return {
    label: entry.data.title,
    href: entryToHref(entry),
    slug: entry.id,
  };
}

function slugToSidebarItem(entriesById: Map<string, DocsEntry>, slug: string): DocsSidebarItem {
  const entry = getEntryForSlug(entriesById, slug);

  if (entry) {
    return entryToSidebarItem(entry);
  }

  return {
    label: slugToTitle(slug),
    href: slugToHref(slug),
    slug,
  };
}

function linkToSidebarItem(item: SidebarLinkItem): DocsSidebarItem {
  return {
    label: item.label,
    href: item.link,
    external: item.external ?? isExternalLink(item.link),
    icon: item.icon,
  };
}

function normalizeSidebarItems(
  items: SidebarItemConfig[],
  entries: DocsEntry[],
  entriesById: Map<string, DocsEntry>,
): DocsSidebarItem[] {
  return items.flatMap((item) => {
    if (typeof item === 'string') {
      return [slugToSidebarItem(entriesById, item)];
    }

    if (isAutogenerateItem(item)) {
      return sortNavItems(
        getAutogeneratedEntries(entries, item.autogenerate.directory).map(toNavItem),
      ).map(navItemToSidebarItem);
    }

    if (isGroupItem(item)) {
      return [
        {
          label: item.label,
          icon: item.icon,
          items: normalizeSidebarItems(item.items, entries, entriesById),
        },
      ];
    }

    if (isLinkItem(item)) {
      return [linkToSidebarItem(item)];
    }

    return [];
  });
}

function sidebarConfigToNav(sidebar: SidebarConfig, entries: DocsEntry[]): DocsSidebarNav {
  const entriesById = getEntryMap(entries);
  const links: DocsSidebarItem[] = [];
  const groups: DocsSidebarGroupNav[] = [];

  for (const item of sidebar.items) {
    if (isGroupItem(item)) {
      groups.push({
        title: item.label,
        items: normalizeSidebarItems(item.items, entries, entriesById),
      });
    } else {
      links.push(...normalizeSidebarItems([item], entries, entriesById));
    }
  }

  return { links, groups };
}

function findItemSectionTitle(
  items: DocsSidebarItem[],
  currentSlug: string,
  sectionTitle: string,
): string | undefined {
  for (const item of items) {
    if (item.slug === currentSlug) {
      return sectionTitle;
    }

    if (item.items) {
      const childTitle = findItemSectionTitle(item.items, currentSlug, sectionTitle);

      if (childTitle) {
        return childTitle;
      }
    }
  }

  return undefined;
}

export function getSidebarSectionTitle(
  sidebar: DocsSidebarNav,
  currentSlug: string,
): string | undefined {
  for (const group of sidebar.groups) {
    const title = findItemSectionTitle(group.items, currentSlug, group.title);

    if (title) {
      return title;
    }
  }

  const linkTitle = findItemSectionTitle(sidebar.links, currentSlug, '');

  return linkTitle || undefined;
}

function getSidebarConfig(currentSection?: string): SidebarConfig | undefined {
  return themeConfig.sidebars.find(
    (sidebar) => getSidebarSectionSlug(sidebar) === currentSection,
  );
}

function sortNavItems(items: DocsNavItem[]): DocsNavItem[] {
  return [...items].sort((left, right) => {
    if (left.order !== right.order) {
      return left.order - right.order;
    }

    return left.title.localeCompare(right.title);
  });
}

export async function getDocsEntries(): Promise<DocsEntry[]> {
  const entries = await getCollection('docs');

  return [...entries].sort((left, right) => {
    const orderDiff = getEntryOrder(left) - getEntryOrder(right);

    if (orderDiff !== 0) {
      return orderDiff;
    }

    return left.data.title.localeCompare(right.data.title);
  });
}

export function entryToHref(entry: DocsEntry): string {
  const basePath = normalizeDocsBasePath(themeConfig.docsBase);

  if (entry.id === 'index') {
    return basePath === '/' ? '/' : `${basePath}/`;
  }

  return basePath === '/' ? `/${entry.id}/` : `${basePath}/${entry.id}/`;
}

export function getCurrentSection(slug: string | undefined): string | undefined {
  if (!slug || slug === 'index') {
    return undefined;
  }

  const [section] = slug.split('/');
  return section || undefined;
}

export async function getDocsNavigation(
  currentSection?: string,
): Promise<DocsSectionNav[]> {
  const entries = await getDocsEntries();
  const itemsBySection = new Map<string, DocsNavItem[]>();

  for (const entry of entries) {
    const item = toNavItem(entry);

    if (!item.section) {
      continue;
    }

    const sectionItems = itemsBySection.get(item.section) ?? [];
    sectionItems.push(item);
    itemsBySection.set(item.section, sectionItems);
  }

  return themeConfig.sidebars.map((sidebar) => {
    const sectionSlug = getSidebarSectionSlug(sidebar);
    const items = sortNavItems(itemsBySection.get(sectionSlug) ?? []);
    const basePath = normalizeDocsBasePath(themeConfig.docsBase);
    const href =
      items[0]?.href ??
      (basePath === '/' ? `/${sectionSlug}/` : `${basePath}/${sectionSlug}/`);

    return {
      slug: sectionSlug,
      label: sidebar.label,
      icon: sidebar.icon,
      href,
      active: sectionSlug === currentSection,
      items,
    };
  });
}

export async function getSidebarNavigation(
  currentSection?: string,
): Promise<DocsSidebarNav> {
  if (!currentSection) {
    return { links: [], groups: [] };
  }

  const entries = await getDocsEntries();
  const sidebarConfig = getSidebarConfig(currentSection);

  if (sidebarConfig) {
    return sidebarConfigToNav(sidebarConfig, entries);
  }

  const items = sortNavItems(
    entries
      .map(toNavItem)
      .filter((item) => item.section === currentSection),
  ).map(navItemToSidebarItem);

  return {
    links: [],
    groups: items.length > 0 ? [{ title: currentSection, items }] : [],
  };
}
