name: Site

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - '*.lock'
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
          registry-url: https://npm.pkg.github.com
          scope: "@prosefly"

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
        run: |
          pnpm install --frozen-lockfile
          pnpm install @prosefly/astro-openapi

      - name: Test package
        run: pnpm test

      - name: Clone pro template
        uses: actions/checkout@v7
        with:
          repository: prosefly/astro-template-lotus-pro
          path: pro
          token: ${{ github.token }}

      - name: Prepare pro feature
        run: |
          mv pro/src/pages/api src/pages/
          cp pro/src/openapi/cafe.yaml src/openapi.yaml
          cp tools/pro/astro.config.ts ./
          cp tools/pro/content.config.ts ./src/

      - name: Check site
        run: pnpm check

      - name: Build site
        env:
          GH_TOKEN: ${{ github.token }}
        run: pnpm build

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist

  deploy:
    name: Publish site
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
